// Generated by CoffeeScript 1.9.3
(function() {
  var arg, i, len, ref;

  ref = process.argv;
  for (i = 0, len = ref.length; i < len; i++) {
    arg = ref[i];
    console.log(arg);
  }

}).call(this);
