// Generated by CoffeeScript 1.9.3
"use strict";
var title;

$(document).ready(function() {
  $("button").click(function() {
    $.getJSON("http://api.openweathermap.org/data/2.5/forecast/city?id=5380748&APPID=510f17fc4351880193a58f228f89faa5&units=imperial", function(result) {
      $("div").text("The weather in " + result.city.name + " is " + result.list[0].main.temp + " degrees");
      $("div").append("<br>");
    });
  });
});

title = document.getElementsByTagName('title')[0];
