// Generated by CoffeeScript 1.9.3
var add, bob, contacts, list, mary, printPerson, search;

bob = {
  firstName: "Bob",
  lastName: "Jones",
  phoneNumber: "(650) 777-777",
  email: "bob.jones@example.com"
};

mary = {
  firstName: "Mary",
  lastName: "Johnson",
  phoneNumber: "(650) 888-8888",
  email: "mary.johnson@example.com"
};

contacts = [bob, mary];

printPerson = function(person) {
  console.log(person.firstName + " " + person.lastName);
};

list = function() {
  var contactsLength, i, len, p;
  contactsLength = contacts.length;
  for (i = 0, len = contacts.length; i < len; i++) {
    p = contacts[i];
    printPerson(p);
  }
};

search = function(lastName) {
  var i, len, person;
  for (i = 0, len = contacts.length; i < len; i++) {
    person = contacts[i];
    if (person.lastName === lastName) {
      printPerson(person);
    }
  }
};

add = function(firstName, lastName, phoneNumber, email) {
  contacts[contacts.length] = {
    firstName: firstName,
    lastName: lastName,
    phoneNumber: phoneNumber,
    email: email
  };
};

add("Barak", "Obama", "111-111-1111", "president@whitehouse.gov");

list();
