// Generated by CoffeeScript 1.4.0
var add, bob, contacts, list, mary, printPerson, search;

bob = {
  firstName: "Bob",
  lastName: "Jones",
  phoneNumber: "(650) 777-777",
  email: "bob.jones@example.com"
};

mary = {
  firstName: "Mary",
  lastName: "Johnson",
  phoneNumber: "(650) 888-8888",
  email: "mary.johnson@example.com"
};

contacts = [bob, mary];

printPerson = function(person) {
  console.log(person.firstName + " " + person.lastName);
};

list = function() {
  var contactsLength, p, _i, _len;
  contactsLength = contacts.length;
  for (_i = 0, _len = contacts.length; _i < _len; _i++) {
    p = contacts[_i];
    printPerson(p);
  }
};

search = function(lastName) {
  var person, _i, _len;
  for (_i = 0, _len = contacts.length; _i < _len; _i++) {
    person = contacts[_i];
    if (person.lastName === lastName) {
      printPerson(person);
    }
  }
};

add = function(firstName, lastName, phoneNumber, email) {
  contacts[contacts.length] = {
    firstName: firstName,
    lastName: lastName,
    phoneNumber: phoneNumber,
    email: email
  };
};

add("Barak", "Obama", "111-111-1111", "president@whitehouse.gov");

list();
