// Generated by CoffeeScript 1.4.0
var friends, list, search;

friends = {
  bill: {
    firstName: "Bill",
    lastName: "Gates",
    number: "lol idk",
    address: []
  },
  steve: {
    firstName: "Steve",
    lastName: "Jobs",
    number: "lol idk",
    address: []
  }
};

list = function(object) {
  var key, _results;
  _results = [];
  for (key in object) {
    _results.push(console.log(key));
  }
  return _results;
};

search = function(firstName) {
  var key, value, _results;
  _results = [];
  for (key in friends) {
    value = friends[key];
    if (friends[key].firstName === firstName) {
      console.log(firstName);
      _results.push(friends[key]);
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};
