// Generated by CoffeeScript 1.9.3
var user;

user = prompt("WHAT IS YOUR FAVORITE COLOR?").toLowerCase();

switch (user) {
  case 'yes':
    if ('yes' && 'no') {
      console.log('well now youve done it you have!');
    } else {
      console.log('thats odd');
    }
    break;
  case 'blue! wait no, red!':
    console.log('you were thrown off the bridge!');
    break;
  case 'no':
    if ('no' || 'potato') {
      console.log('Im no longer sure what Im doing');
    }
    console.log('who does know?');
    break;
  default:
    console.log('something else happened');
}
