// Generated by CoffeeScript 1.4.0
var i, _i;

for (i = _i = 1; _i <= 20; i = _i += 1) {
  if (i % 3 === 0 && i % 5 === 0) {
    console.log("FizzBuzz");
  } else if (i % 3 === 0) {
    console.log("Fizz");
  } else if (i % 5 === 0) {
    console.log("Buzz");
  } else {
    console.log(i);
  }
}
