// Generated by CoffeeScript 1.9.3
var aNumber, aString, anObj;

anObj = {
  job: "I'm an object!"
};

aNumber = 42;

aString = "I'm a string!";

console.log(typeof anObj);

console.log(typeof aNumber);

console.log(typeof aString);
