// Generated by CoffeeScript 1.9.3
var Emperor, Penguin, emperor;

Penguin = (function() {
  function Penguin(name) {
    this.name = name;
    this.numLegs = 2;
  }

  return Penguin;

})();

Emperor = (function() {
  function Emperor(name) {
    this.name = name;
  }

  return Emperor;

})();

Emperor.prototype = new Penguin;

emperor = new Emperor('potooooooooo');

console.log(emperor.numLegs);
