// Generated by CoffeeScript 1.9.3
var friends, list, search;

friends = {
  bill: {
    firstName: "Bill",
    lastName: "Gates",
    number: "lol idk",
    address: []
  },
  steve: {
    firstName: "Steve",
    lastName: "Jobs",
    number: "lol idk",
    address: []
  }
};

list = function(object) {
  var key, results;
  results = [];
  for (key in object) {
    results.push(console.log(key));
  }
  return results;
};

search = function(firstName) {
  var key, results, value;
  results = [];
  for (key in friends) {
    value = friends[key];
    if (friends[key].firstName === firstName) {
      console.log(firstName);
      results.push(friends[key]);
    } else {
      results.push(void 0);
    }
  }
  return results;
};
