// Generated by CoffeeScript 1.9.3
var Person, gabby, james;

james = {
  job: "programmer",
  married: false
};

Person = function(job, married) {
  this.job = job;
  this.married = married;
};

gabby = new Person("student", true);
