// Generated by CoffeeScript 1.9.3
var PORT, dispatcher, handleRequest, http, server;

http = require('http');

dispatcher = require('httpdispatcher');

PORT = process.argv[2];

console.log(PORT);

if (PORT === void 0 || PORT === null) {
  PORT = 8808;
}

handleRequest = function(request, response) {
  var error;
  try {
    console.log(request.url);
    dispatcher.dispatch(request, response);
  } catch (_error) {
    error = _error;
    console.log(error);
  }
};

dispatcher.onGet("/page1", function(req, res) {
  res.writeHead(200, {
    'Content - Type': 'text/plain'
  });
  res.end("Page One");
});

dispatcher.onGet("/", function(req, res) {
  res.writeHead(200, {
    'Content - Type': 'text/plain'
  });
  res.end("Root Page");
});

dispatcher.onPost("/post1", function(req, res) {
  res.writeHead(200, {
    'Content - Type': 'text/plain'
  });
  res.end("Got Post");
});

server = http.createServer(handleRequest);

server.listen(PORT, function() {
  console.log("Server running on localhost port " + PORT + "...");
});
