// Generated by CoffeeScript 1.9.3
var PORT, handleRequest, http, server;

http = require('http');

PORT = 8808;

handleRequest = function(request, response) {
  response.end("It works: path hit = " + request.url);
};

server = http.createServer(handleRequest);

server.listen(PORT, function() {
  console.log("Server running on localhost:" + PORT + "...");
});
