// Generated by CoffeeScript 1.9.3
var object1, object2, object3, object4;

object1 = new Object();

object2 = new Object();

object3 = new Object();

object4 = {
  name: "another way to create an object"
};

object1.potato = "potato";

object2.bus = "ran over 1 child";

object3.age = "a billion yeaaaaaaaaaaars";
