// ==UserScript==
// @name        Exclude Subreddits
// @namespace   exclude-subreddits
// @include     https://www.reddit.com/*
// @version     1
// @grant       none
// ==/UserScript==;
// Generated by CoffeeScript 1.9.3
'use strict';
(function() {
  var BANNED_SUBREDDITS, content, contents, div, divs, i, j, len, len1, subreddit;

  BANNED_SUBREDDITS = ['The_Donald', 'AdviceAnimals', 'AskReddit', 'cringepics', 'Conservative', 'CringeAnarchy', 'EnoughTrumpSpam', 'atheism', 'rage', 'Jokes', /*put subreddit names here*/];

  contents = document.getElementsByClassName('content');

  for (i = 0, len = contents.length; i < len; i++) {
    content = contents[i];
    divs = content.getElementsByTagName('div');
    for (j = 0, len1 = divs.length; j < len1; j++) {
      div = divs[j];
      if (div.hasAttribute('data-subreddit')) {
        subreddit = div.getAttribute('data-subreddit');
        if (BANNED_SUBREDDITS.includes(subreddit)) {
          console.log("Exclude Subreddit blocked " + subreddit);
          div.remove();
        }
      }
    }
  }

}).call(this);
